version: "3.3"
services:
  storage:
    # FIXME
    # image: gitlab-registry.lre.epita.fr/soduco/directory-annotator-back
     build:
      context: ..
      dockerfile: ./docker/deploy-debian-stable.dockerfile
      # dockerfile: ./docker/test_autofetch.dockerfile  # variant with automatic fetch from gitlab package repo
     ports:
        - "${REVERSE_PORT}:8000"
     env_file:
        - .env
     environment:
        - SODUCO_SETTINGS=/app/settings.cfg
        - SCRIPT_NAME=/soduco/directory-annotator/storage
     secrets:
        - auth_tokens
     volumes:
        - type: bind
          source: ${PATH_DIRECTORIES}
          target: "/data/directories"
          read_only: true
        - type: bind
          source: ./settings.cfg
          target: "/app/settings.cfg"
        - type: volume
          source: soduco-annotations-data
          target: "/data/annotations"
          volume:
            nocopy: true

volumes:
  soduco-annotations-data:

secrets:
  auth_tokens:
    file: .secret-keys
